import Detail from "@/components/Details/Detail";
import Project from "@/components/Project/Project";
import { projectBYYId } from "@/services/project";
import React from "react";

// export async function generateMetadata({ params, searchParams }) {
//   const product = await projectBYYId(params.id);
//   return { title: product.name };
// }
export const generateMetadata = async ({ params }) => {
  const productDetailsParams = await projectBYYId(params.details);

  // console.log("endh shave bhai", productDetailsParams);
   return {
    title: productDetailsParams.name,
    description: productDetailsParams.desc,
    keyword:[
      "Modern Villa",
      "Vintage Home",
      "Heritage House",
      "Contemporary Residence",
      "Traditional Cottage",
      "Luxury Mansion",
      "Tiny House",
      "Eco-Friendly Home",
      "Minimalist Abode",
      "Rustic Cabin",
      "Art Deco Dwelling",
      "Colonial Homestead",
      "Beachfront Bungalow",
      "Urban Loft",
      "Mountain Retreat",
      "Mediterranean Villa",
      "Craftsman Bungalow",
      "Mid-Century Modern House",
      "Countryside Farmhouse",
      "Treehouse Hideaway",
      "Floating Houseboat",
      "Geodesic Dome",
      "Sustainable Eco-House",
      "Bohemian Haven",
      "Japanese Zen Home",
      "Victorian Manor",
      "French Château",
      "Castle",
      "A-Frame Cabin",
      "Split-Level House",
      "Glass House",
      "Gothic Mansion",
      "Lighthouse Residence",
      "Scandinavian Design Home",
      "Swiss Chalet",
      "Spanish Revival House",
      "Mountain Chalet",
      "Tree-Topper Retreat",
      "Log Cabin",
      "Artistic Studio",
      "Container Home",
      "Cave Dwelling",
      "Floating Island Residence",
      "Futuristic Smart Home",
      "Ranch House",
      "Tudor-style Home",
      "Greek Revival Estate",
      "Cottagecore Cottage",
      "Boho Chic Villa",
      "Zen Minimalist Retreat",
      "Hobbit House",
      "Egyptian Pyramid Home",
      "Roman Villa",
      "Garden Oasis Home",
      "Winery Estate",
      "Beach House",
      "Island Getaway",
      "Beachfront Palace",
      "Luxury Yacht Home",
      "Historical Landmark Home",
      "Floating Castle",
      "Oceanside Villa",
      "Nomadic Yurt",
      "Suburban Family House",
      "City Loft Apartment",
      "Classic Townhouse",
      "Cabin in the Woods",
      "Castle on the Hill",
      "Cottage by the Sea",
      "Modernist Masterpiece",
      "Solar-Powered Home",
      "Architectural Wonder",
      "African Safari Lodge",
      "Alpine Chalet",
      "Asian Pagoda House",
      "Bamboo Bungalow",
      "Baroque Palace",
      "Brick Colonial Home",
      "Butterfly-roof House",
      "Cape Cod Cottage",
      "Carriage House",
      "Charleston-style Home",
      "Chateau on the Lake",
      "Colonial Revival Residence",
      "Contemporary Art House",
      "Country Manor",
      "Czech Cubist House",
      "Desert Oasis Retreat",
      "Fairy-tale Castle",
      "Floating Pagoda",
      "Floating Palace",
      "Frank Lloyd Wright Design",
      "French Country Chateau",
      "Georgian Mansion",
      "Gingerbread House",
      "Glass Pyramid",
      "Greek Island Villa",
      "Hawaiian Tiki Hut",
      "Hollywood Hills Estate",
      "Indian Palace",
      "Italian Villa",
      "Japanese Tea House",
      "Jetsetter's Mansion",
      "Lakeside Cabin",
      "Lighthouse Residence",
      "Mediterranean Palace",
      "Mid-century Ranch",
      "Minimalist Cube House",
      "Moroccan Riad",
      "Nordic Igloo",
      "Oriental Palace",
      "Prairie-style Home",
      "Queen Anne Victorian",
      "Roman Colosseum-inspired Home",
      "Shabby Chic Cottage",
      "Ski Chalet",
      "Spanish Courtyard House",
      "Starship-inspired Home",
      "Surrealist House",
      "Swiss Alps Lodge",
      "Thai Bamboo House",
      "Tropical Paradise Villa",
      "Venetian Palazzo",
      "Victorian Gingerbread House",
      "Viking Longhouse",
      "Wild West Saloon",
      "Woodland Cabin",
    ],
  };
};
const page = async ({ params }) => {
  const productDetailsParams = await projectBYYId(params.details);
  // return <Detail />;
  return <Project item={productDetailsParams && productDetailsParams.data} />;
};

export default page;
